### ISSUE TITLE
复现vehicleID结果

### ISSUE THREAD

**Issue by pswena** [damo-cv/TransReID#57]
您好！根据您在vehicleID上的配置batch_size是256，我没有那么大的显存，我尝试把batch_size调小，除了修改学习率还有epoch需要修改吗？如果您之前有做过这样的工作能否告诉一下配置情况，谢谢！

**Comment by pswena** [comment]
![image](https://user-images.githubusercontent.com/44701958/170166007-61c45bcb-d78b-49c2-8c36-a4da3ce6ab68.png)
还有就是您的论文中用ViT-B/16来做backbone，同时使用SIE_VIEW和SIE_CAMERA的情况是没有结果吗？如果能回答万分感激

**Comment by michuanhaohao** [comment]
> ![image](https://user-images.githubusercontent.com/44701958/170166007-61c45bcb-d78b-49c2-8c36-a4da3ce6ab68.png) 还有就是您的论文中用ViT-B/16来做backbone，同时使用SIE_VIEW和SIE_CAMERA的情况是没有结果吗？如果能回答万分感激

有的，但是只有VeRI776数据集同时提供的viewpoint和camera标签，所以只有VeRIfy776有这个结果，你可以看SIE的ablation study

**Comment by michuanhaohao** [comment]
> 您好！根据您在vehicleID上的配置batch_size是256，我没有那么大的显存，我尝试把batch_size调小，除了修改学习率还有epoch需要修改吗？如果您之前有做过这样的工作能否告诉一下配置情况，谢谢！

这个我确定参数对结果是否有影响，一般单卡64是比较好的参数，修改batch size学习率需要做线性缩放，其他的不需要修改，BS会对结果有点影响。目前有一种trick是BS=32，两个batch做一次反传来近似BS=64，但是没试过。

**Comment by pswena** [comment]
> > 您好！根据您在vehicleID上的配置batch_size是256，我没有那么大的显存，我尝试把batch_size调小，除了修改学习率还有epoch需要修改吗？如果您之前有做过这样的工作能否告诉一下配置情况，谢谢！
> 
> 这个我确定参数对结果是否有影响，一般单卡64是比较好的参数，修改batch size学习率需要做线性缩放，其他的不需要修改，BS会对结果有点影响。目前有一种trick是BS=32，两个batch做一次反传来近似BS=64，但是没试过。

好的，谢谢，我已经再试了。

**Comment by pswena** [comment]
> > ![image](https://user-images.githubusercontent.com/44701958/170166007-61c45bcb-d78b-49c2-8c36-a4da3ce6ab68.png) 还有就是您的论文中用ViT-B/16来做backbone，同时使用SIE_VIEW和SIE_CAMERA的情况是没有结果吗？如果能回答万分感激
> 
> 有的，但是只有VeRI776数据集同时提供的viewpoint和camera标签，所以只有VeRIfy776有这个结果，你可以看SIE的ablation study

嗯嗯，好的，多谢！然后还有就是您的实验没有跑veri-wild这个数据集吗？我看到好像没有这个。然后就是我看了下您在vehicle下默认的配置(如下图片)，好像并没有加入sie_view和sie_camera，默认是跑baseline是吗？再次感谢作者您的回答，太感谢了！
![image](https://user-images.githubusercontent.com/44701958/170176331-a618b848-d923-406f-ab74-7a30214ecb17.png)

**Comment by michuanhaohao** [comment]
> > > ![image](https://user-images.githubusercontent.com/44701958/170166007-61c45bcb-d78b-49c2-8c36-a4da3ce6ab68.png) 还有就是您的论文中用ViT-B/16来做backbone，同时使用SIE_VIEW和SIE_CAMERA的情况是没有结果吗？如果能回答万分感激
> > 
> > 
> > 有的，但是只有VeRI776数据集同时提供的viewpoint和camera标签，所以只有VeRIfy776有这个结果，你可以看SIE的ablation study
> 
> 嗯嗯，好的，多谢！然后还有就是您的实验没有跑veri-wild这个数据集吗？我看到好像没有这个。然后就是我看了下您在vehicle下默认的配置(如下图片)，好像并没有加入sie_view和sie_camera，默认是跑baseline是吗？再次感谢作者您的回答，太感谢了！ ![image](https://user-images.githubusercontent.com/44701958/170176331-a618b848-d923-406f-ab74-7a30214ecb17.png)

没有跑过wild，这个yml文件没有加入sie_view和sie_camera，加sie可能在别的yml里面，或者自己加一下也可以

**Comment by pswena** [comment]
这是我的配置文件：
![089a84a17c996c86d7336cb041f39b5](https://user-images.githubusercontent.com/44701958/171359775-f2b24da3-1163-4791-9a06-08148d6df53a.png)
然后我在运行的时候特地输出了下在vehicleID数据集上的view是等于1，所以就出现了上面我所讲的错误，我感觉会不会是下面这里都改成>1呢？
![9f602e537135af1eb059e5b278c9280](https://user-images.githubusercontent.com/44701958/171360009-5e22909c-c5c9-4c9d-82c9-b1259584a023.png)

**Comment by pswena** [comment]
这个是我报的错：
Traceback (most recent call last):
  File "train.py", line 86, in <module>
    num_query, args.local_rank
  File "/mnt/nfs-storage-node-09/TransReID-main/processor/processor.py", line 58, in do_train
    score, feat = model(img, target, cam_label=target_cam, view_label=target_view )
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nfs-storage-node-09/TransReID-main/model/make_model.py", line 310, in forward
    features = self.base(x, cam_label=cam_label, view_label=view_label)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nfs-storage-node-09/TransReID-main/model/backbones/vit_pytorch.py", line 407, in forward
    x = self.forward_features(x, cam_label, view_label)
  File "/mnt/nfs-storage-node-09/TransReID-main/model/backbones/vit_pytorch.py", line 387, in forward_features
    x = x + self.pos_embed + self.sie_xishu * self.sie_embed[view_id]
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'TransReID' object has no attribute 'sie_embed'

**Comment by michuanhaohao** [comment]
> vehicleID

vehicleID数据集没有view标签，只有camera标签，原始论文里vehicleID没有跑SIE。如果你需要跑，你只能把SIE_CAMERA设置为True，SIE_VIEW设置为false。vehicleID里面的viewid=1只是占位符，没有任何意义。
