### ISSUE TITLE
The size of tensor a (6) must match the size of tensor b (160) at non-singleton dimension 0

### ISSUE THREAD

**Issue by ShivankYadav** [damo-cv/TransReID#70]
Hi, I am trying to run the pretrained vit_transreid_veri.pth weights directly for testing purposes. In the vit_transreid.yml, I tried with MODEL.PRETRAIN_CHOICE as both imagenet and self with models "jx_vit_base_p16_224-80ecf9dd.pth" and "vit_transreid_veri.pth" but still getting the same error during test weights loading phase. 
===========building transformer with JPM module ===========
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    model.load_param(cfg.TEST.WEIGHT)
  File "/app/model/make_model.py", line 376, in load_param
    self.state_dict()[i.replace('module.', '')].copy_(param_dict[i])
RuntimeError: The size of tensor a (6) must match the size of tensor b (160) at non-singleton dimension 0

**Comment by heshuting555** [comment]
The possible reason is that the size of position embedding or side embedding does not match, you can print `print(i, self.state_dict()[i.replace('module.', '')].shape, param_dict[i].shape)` to know why the error occurs.

**Comment by Hocason** [comment]
> The possible reason is that the size of position embedding or side embedding does not match, you can print `print(i, self.state_dict()[i.replace('module.', '')].shape, param_dict[i].shape)` to know why the error occurs.

Hi, 
Why the dimension of `base.sie_embed` changes when I use different datasets? The transformer type is vit_base_patch16_224_TransReID. What is `base.sie_embed`?

**Comment by ledinhtri97** [comment]
Hi @heshuting555 , Seem the size dimension changes when use other dataset. How to load pre-trained model and test with difference data?

Thank you

**Comment by kp97524** [comment]
Hi @heshuting555,

Is there any update on this issue? I am trying to load the model trained on VeRi dataset and test on MarketPlace dataset!

Has the same requirement as @ledinhtri97

Any help is super appreciated!
