### ISSUE TITLE
我加入了OccludedREID数据集的测试，但是运行的时候出现以下错误，求解答

### ISSUE THREAD

**Issue by liyexin-1** [damo-cv/TransReID#79]
Traceback (most recent call last):
  File "/TransReID-main/test.py", line 46, in <module>
    model.load_param(cfg.TEST.WEIGHT)
  File "/TransReID-main/model/make_model.py", line 386, in load_param
    self.state_dict()[i.replace('module.', '')].copy_(param_dict[i])
KeyError: 'base.sie_embed'

**Comment by Dddzihan** [comment]
这个数据集没有相机参数
