### ISSUE TITLE
how to solve

### ISSUE THREAD

**Issue by Jason1017748116** [damo-cv/TransReID#84]
Traceback (most recent call last):
  File "D:\expremient\TransReID-main\test.py", line 43, in <module>
    train_loader, train_loader_normal, val_loader, num_query, num_classes, camera_num, view_num = make_dataloader(cfg)
  File "D:\expremient\TransReID-main\datasets\make_dataloader.py", line 61, in make_dataloader
    dataset = __factory[cfg.DATASETS.NAMES](root=cfg.DATASETS.ROOT_DIR)
  File "D:\expremient\TransReID-main\datasets\veri.py", line 31, in __init__
    self._check_before_run()
  File "D:\expremient\TransReID-main\datasets\veri.py", line 75, in _check_before_run
    raise RuntimeError("'{}' is not available".format(self.train_dir))
RuntimeError: 'TransReID-main/data\VeRi\image_train' is not available

**Comment by Jason1017748116** [comment]
无论我是改成绝对路径还是相对路径都是这样

**Comment by mxl1990** [comment]
> Traceback (most recent call last): File "D:\expremient\TransReID-main\test.py", line 43, in train_loader, train_loader_normal, val_loader, num_query, num_classes, camera_num, view_num = make_dataloader(cfg) File "D:\expremient\TransReID-main\datasets\make_dataloader.py", line 61, in make_dataloader dataset = __factory[cfg.DATASETS.NAMES](root=cfg.DATASETS.ROOT_DIR) File "D:\expremient\TransReID-main\datasets\veri.py", line 31, in **init** self._check_before_run() File "D:\expremient\TransReID-main\datasets\veri.py", line 75, in _check_before_run raise RuntimeError("'{}' is not available".format(self.train_dir)) RuntimeError: 'TransReID-main/data\VeRi\image_train' is not available

你这路径一下是/ 一下是\，都不检查一下的吗
